#!/usr/local/bin/python
"""College Nicknames Alexa Skill

This sample demonstrates a simple skill built with the Amazon Alexa Skills Kit.
The Intent Schema, Custom Slots, and Sample Utterances for this skill, as well
as testing instructions are located at http://amzn.to/1LzFrj6

For additional samples, visit the Alexa Skills Kit Getting Started guide at
http://amzn.to/1LGWsLG
"""

# ------- Skill specific business logic -------
GAME_LENGTH = 5
SKILL_NAME = "College Nicknames"

QUESTIONS = [
    {"Abilene Christian University": ["Wildcats"]},
    {"Adams State": ["Grizzly Bear", "Grizzlies"]},
    {"Adelphi": ["Cougar", "Panthers"]},
    {"Adrian College": ["Bulldogs"]},
    {"Air Force": ["Falcons"]},
    {"Akron": ["Zips"]},
    {"Alabama Crimson": ["Tide"]},
    {"Alabama Birmingham": ["Blazers"]},
    {"Alabama Huntsville": ["Chargers"]},
    {"Alabama A and M": ["Bulldogs", "Lady Bulldogs"]},
    {"Alabama State": ["Hornets", "Lady Hornets"]},
    {"Alaska Anchorage": ["Seawolves"]},
    {"Alaska Fairbanks": ["Nanooks"]},
    {"Albany": ["Great Danes"]},
    {"Albright College": ["Lions"]},
    {"Alcorn State": ["Braves", "Lady Braves"]},
    {"Albertus Magnus College": ["Falcons"]},
    {"Alderson Broaddus College": ["Battlers"]},
    {"Alfred University": ["Saxons"]},
    {"Alice Lloyd College": ["Eagles"]},
    {"Alvernia University": ["Crusaders"]},
    {"American International College": ["Yellowjackets"]},
    {"American University": ["Eagles"]},
    {"Amherst College": ["Lord Jeffs"]},
    {"Anderson University, Indiana": ["Ravens"]},
    {"Anderson University, South Carolina": ["Trojans"]},
    {"Angelo State University": ["Rams Rambelles", "'Belles"]},
    {"Appalachian State University": ["Mountaineers"]},
    {"Arcadia University": ["Knights"]},
    {"Arizona": ["Wildcats"]},
    {"Arizona State University": ["Sun Devils"]},
    {"Arkansas": ["Razorbacks"]},
    {"Arkansas Little Rock": ["Trojans"]},
    {"Arkansas Monticello": ["Boll Weevils", "Cotton Blossoms"]},
    {"Arkansas Pine Bluff": ["Golden Lions"]},
    {"Arkansas State University": ["Red Wolves"]},
    {"Arkansas Tech University": ["Wonder Boys", "Golden Suns"]},
    {"Army": ["Black Knights"]},
    {"ASA College, Miami": ["Silver Storm"]},
    {"ASA College, New York": ["Avengers"]},
    {"Ashford University": ["Saints"]},
    {"Ashland University": ["Eagles"]},
    {"Association Free Lutheran Bible School and Seminary": ["Conquerors"]},
    {"Assumption College": ["Greyhounds"]},
    {"Auburn University": ["Tigers", "Plainsmen"]},
    {"Auburn University at Montgomery": ["Senators"]},
    {"Augsburg College": ["Auggies"]},
    {"Augustana College": ["Vikings"]},
    {"Aurora University": ["Spartans"]},
    {"Austin College": ["Kangaroos"]},
    {"Austin Peay State University": ["Governors", "Lady Govs"]},
    {"Ave Maria University": ["Gyrenes"]},
    {"Avila University": ["Eagles"]},
    {"Azusa Pacific University": ["Cougars"]},
    {"Babson College": ["Beavers"]},
    {"Baker University": ["Wildcats"]},
    {"Baldwin Wallace College": ["Yellow Jackets"]},
    {"Ball State University": ["Cardinals"]},
    {"Bard College": ["Raptors"]},
    {"Barry University": ["Buccaneers"]},
    {"Bates College": ["Bobcats"]},
    {"Baylor University": ["Bears", "Lady Bears"]},
    {"Bellevue University": ["Bruins"]},
    {"Belmont University": ["Bruins"]},
    {"Belmont Abbey College": ["Crusaders"]},
    {"Beloit College": ["Buccaneers"]},
    {"Bemidji State University": ["Beavers"]},
    {"Benedict College": ["Tigers"]},
    {"Benedictine College": ["Ravens"]},
    {"Bentley College": ["Falcons"]},
    {"Berea College": ["Mountaineers"]},
    {"Bethany College, Kansas": ["Swedes"]},
    {"Bethany College, West Virginia": ["Bison"]},
    {"Bethel College, Indiana": ["Pilots"]},
    {"Bethel College, Kansas": ["Threshers"]},
    {"Bethel University, Minnesota": ["Royals"]},
    {"Bethel University, Tennessee": ["Wildcats"]},
    {"Bethune Cookman College": ["Wildcats"]},
    {"Binghamton University": ["Bearcats"]},
    {"Birmingham Southern College": ["Panthers"]},
    {"Black Hills State University": ["Yellow Jackets"]},
    {"Blinn College": ["Buccaneers"]},
    {"Bloomfield College": ["Deacons"]},
    {"Bloomsburg University": ["Huskies"]},
    {"Bluefield College": ["Rams"]},
    {"Bluefield State College": ["Big Blues", "Lady Blues"]},
    {"Bluffton University": ["Beavers"]},
    {"Boise State University": ["Broncos"]},
    {"Boston College": ["Eagles"]},
    {"Boston University": ["Terriers"]},
    {"Bowling Green State University": ["Falcons"]},
    {"Bowdoin College": ["Polar Bears"]},
    {"Bowie State University": ["Bulldogs"]},
    {"Bradley University": ["Braves"]},
    {"Brandeis University": ["Judges"]},
    {"Briarcliffe College": ["Seahawks"]},
    {"Brigham Young University": ["Cougars"]},
    {"Brigham Young University, Hawaii": ["Seasiders"]},
    {"Bryant University": ["Bulldogs"]},
    {"Brooklyn College": ["Bulldogs"]},
    {"Broward College": ["Seahawks"]},
    {"Brown University": ["Bears"]},
    {"Bucknell University": ["Bison"]},
    {"Buena Vista University": ["Beavers"]},
    {"Buffalo": ["Bulls"]},
    {"Buffalo State College": ["Bengals"]},
    {"Butler University": ["Bulldogs"]},
    {"Cabrini College": ["Cavaliers"]},
    {"University of California, Berkeley": ["Golden Bears"]},
    {"University of California, Davis": ["Aggies"]},
    {"University of California, Irvine": ["Anteaters"]},
    {"University of California, Merced": ["Golden Bobcats"]},
    {"University of California, Riverside": ["Highlanders"]},
    {"University of California, San Diego": ["Tritons"]},
    {"University of California, Santa Barbara": ["Gauchos"]},
    {"University of California, Santa Cruz": ["Banana Slugs"]},
    {"University of California, Los Angeles": ["Bruins"]},
    {"California Lutheran University": ["Kingsmen", "Regals"]},
    {"California Maritime Academy": ["Keelhaulers"]},
    {"California State Polytechnic University, Pomona": ["Broncos"]},
    {"California Polytechnic State University San Luis Obispo": ["Mustangs"]},
    {"California State University, Bakersfield": ["Roadrunners"]},
    {"California State University, Channel Islands": ["Dolphins"]},
    {"California State University, Chico": ["Wildcats"]},
    {"California State University, East Bay": ["Pioneers"]},
    {"California State University, Fresno": ["Bulldogs"]},
    {"California State University, Fullerton": ["Titans"]},
    {"California State University, Humboldt": ["Jacks"]},
    {"California State University, Long Beach": ["49ers"]},
    {"California State University, Los Angeles": ["Golden Eagles"]},
    {"California State University, Northridge": ["Matadors"]},
    {"California State University, San Bernardino": ["Coyotes"]},
    {"California State University, San Diego": ["Aztecs"]},
    {"California State University, San Francisco": ["Gators"]},
    {"California State University, San Jose": ["Spartans"]},
    {"California State University, Sacramento": ["Hornets"]},
    {"California State University, Sonoma": ["Seawolves"]},
    {"California State University, Stanislaus": ["Warriors"]},
    {"California University of Pennsylvania": ["Vulcans"]},
    {"Calvin College": ["Knights", "Lady Knights"]},
    {"Campbell University": ["Fighting Camels"]},
    {"Campbellsville University": ["Tigers"]},
    {"Canisius College": ["Golden Griffins"]},
    {"Cankdeska Cikana Community College": ["C4"]},
    {"Capital University": ["Crusaders"]},
    {"Cardinal Stritch University": ["Wolves"]},
    {"Carleton College": ["Knights"]},
    {"Carnegie Mellon University": ["Tartans"]},
    {"Carson Newman College": ["Eagles"]},
    {"Carthage College": ["Red Men", "Lady Reds"]},
    {"Case Western Reserve University": ["Spartans"]},
    {"Castleton State College": ["Spartans"]},
    {"The Catholic University of America": ["Cardinals"]},
    {"Cazenovia College": ["Wildcats"]},
    {"Centenary College": ["Gentlemen", "Ladies"]},
    {"Central Arkansas": ["Bears", "Sugar Bears"]},
    {"Central Connecticut State University": ["Blue Devils"]},
    {"College of Central Florida": ["Patriots"]},
    {"Central Florida": ["Knights"]},
    {"Central College, Iowa": ["Dutch"]},
    {"Central Methodist University": ["Eagles"]},
    {"Central Michigan University": ["Chippewas"]},
    {"Central Missouri": ["Mules", "Jennies"]},
    {"Central Oklahoma University": ["Bronchos"]},
    {"Central Washington University": ["Wildcats"]},
    {"Centre College": ["Colonels"]},
    {"Cerritos College": ["Falcons"]},
    {"Chadron State College": ["Eagles"]},
    {"Chaminade University": ["Silverswords"]},
    {"Chapman University": ["Panthers"]},
    {"College of Charleston": ["Cougars"]},
    {"Chatham University": ["Cougars"]},
    {"University of Charleston, West Virginia": ["Golden Eagles"]},
    {"Charleston Southern University": ["Buccaneers", "Lady Bucs"]},
    {"Chestnut Hill College": ["Griffins"]},
    {"Cheyney University": ["Wolves"]},
    {"Chicago": ["Maroons"]},
    {"Chicago State University": ["Cougars"]},
    {"Chipola College": ["Indians"]},
    {"Christian Brothers University": ["Buccaneers"]},
    {"Christopher Newport University": ["Captains"]},
    {"Cincinnati": ["Bearcats"]},
    {"Cincinnati Christian University": ["Eagles"]},
    {"The Citadel": ["Bulldogs"]},
    {"Claremont McKenna College": ["Stags", "Athenas"]},
    {"Harvey Mudd College": ["Stags", "Athenas"]},
    {"Scripps College": ["Stags", "Athenas"]},
    {"Clarion University": ["Golden Eagles"]},
    {"Clarkson University": ["Golden Knights"]},
    {"Clarke University": ["Crusaders"]},
    {"Clearwater Christian College": ["Cougars"]},
    {"Clemson University": ["Tigers"]},
    {"Cleveland State University": ["Vikings"]},
    {"Coastal Carolina University": ["Chanticleers", "Lady Chants"]},
    {"Coe College": ["Kohawks"]},
    {"Coker College": ["Cobras"]},
    {"Colby College": ["White Mules"]},
    {"Colgate University": ["Raiders"]},
    {"Colorado": ["Buffaloes"]},
    {"Colorado Colorado Springs": ["Mountain Lions"]},
    {"Colorado College": ["Tigers"]},
    {"Colorado Mesa University": ["Mavericks", "Lady Mavs"]},
    {"Colorado School of Mines": ["Ore Diggers"]},
    {"Colorado State University": ["Rams"]},
    {"Colorado State University Pueblo": ["ThunderWolves"]},
    {"Columbia College, Missouri": ["Cougars"]},
    {"Columbia University": ["Lions"]},
    {"Concord University": ["Mountain Lions", "Lady Lions"]},
    {"Concordia College, Moorhead": ["Cobbers"]},
    {"Concordia College, Selma": ["Hornets"]},
    {"Concordia College, New York": ["Clippers"]},
    {"Concordia University, Ann Arbor": ["Cardinals"]},
    {"Concordia University Chicago": ["Cougars"]},
    {"Concordia University, Irvine": ["Eagles"]},
    {"Concordia University, Nebraska": ["Bulldogs"]},
    {"Concordia University, Portland": ["Cavaliers"]},
    {"Concordia University, Saint Paul": ["Golden Bears"]},
    {"Concordia University Texas": ["Tornadoes"]},
    {"Concordia University Wisconsin": ["Falcons"]},
    {"Connecticut": ["Huskies"]},
    {"Connecticut College": ["Camels"]},
    {"Coppin State University": ["Eagles"]},
    {"Cornell University": ["Big Red"]},
    {"Cornerstone University": ["Golden Eagles"]},
    {"Creighton University": ["Blue Jays"]},
    {"Culver Stockton College": ["Wildcats"]},
    {"Cumberland University": ["Phoenix"]},
    {"Cumberlands": ["Patriots"]},
    {"Dallas Baptist University": ["Patriots"]},
    {"Dakota State University": ["Trojans"]},
    {"Dana College": ["Vikings"]},
    {"Dartmouth College": ["Big Green"]},
    {"Davis and Elkins College": ["Senators"]},
    {"Davenport University": ["Panthers"]},
    {"Davidson College": ["Wildcats"]},
    {"Dayton": ["Flyers"]},
    {"Daytona State College": ["Falcons"]},
    {"Defiance College": ["Yellow Jackets"]},
    {"DePaul University": ["Blue Demons"]},
    {"DePauw University": ["Tigers"]},
    {"Delaware": ["Fightin' Blue Hens"]},
    {"Delaware State University": ["Hornets"]},
    {"Delaware Valley College": ["Aggies"]},
    {"Delta State University": ["Statesmen", "Lady Statesmen"]},
    {"Denison University": ["Big Red"]},
    {"Denver": ["Pioneers"]},
    {"DeSales University": ["Bulldogs"]},
    {"Detroit": ["Titans"]},
    {"Dickinson College": ["Red Devils"]},
    {"District of Columbia": ["Firebirds", "Lady Firebirds"]},
    {"Doane College": ["Tigers"]},
    {"Dordt College": ["Defenders"]},
    {"Dowling College": ["Golden Lions"]},
    {"Drake University": ["Bulldogs"]},
    {"Drew University": ["Rangers"]},
    {"Drexel University": ["Dragons"]},
    {"Duke University": ["Blue Devils"]},
    {"Duquesne University": ["Dukes"]},
    {"Dubuque": ["Spartans"]},
    {"Earlham College": ["Hustlin' Quakers"]},
    {"Eastern Arizona College": ["Gila Monsters"]},
    {"East Carolina University": ["Pirates"]},
    {"East Los Angeles College": ["Huskies", "Lady Huskies"]},
    {"East Stroudsburg University": ["Warriors"]},
    {"East Tennessee State University": ["Buccaneers", "Lady Bucs"]},
    {"East Texas Baptist University": ["Tigers"]},
    {"Eastern Connecticut State University": ["Warriors"]},
    {"Eastern Florida State College": ["Titans"]},
    {"Eastern Illinois University": ["Fighting Panthers"]},
    {"Eastern Kentucky University": ["Colonels", "Lady Colonels"]},
    {"Eastern Michigan University": ["Eagles"]},
    {"Eastern Nazarene College": ["Lions"]},
    {"Eastern New Mexico University": ["Greyhounds", "Zias"]},
    {"Eastern University": ["Eagles"]},
    {"Eastern Washington University": ["Eagles"]},
    {"Eckerd College": ["Tritons"]},
    {"Edinboro University": ["Fighting Scots"]},
    {"Edward Waters College": ["Tigers"]},
    {"El Paso Community College": ["Tejanos", "Lady Tejanos"]},
    {"Elon University": ["Phoenix"]},
    {"Embry Riddle Aeronautical University": ["Eagles"]},
    {"Emory University": ["Eagles"]},
    {"Emporia State University": ["Hornets"]},
    {"Endicott College": ["Gulls"]},
    {"Erskine College": ["Flying Fleet"]},
    {"Evangel University": ["Crusaders"]},
    {"Evansville": ["Purple Aces"]},
    {"Evergreen State College": ["Geoducks"]},
    {"Fairleigh Dickinson University, Florham Campus": ["Devils"]},
    {"Fairleigh Dickinson University, Metropolitan Campus": ["Knights"]},
    {"Fairfield University": ["Stags"]},
    {"Fairmont State University": ["Falcons"]},
    {"Faulkner University": ["Eagles"]},
    {"Ferris State University": ["Bulldogs"]},
    {"Felician College": ["Golden Falcons"]},
    {"Finlandia University": ["Lions"]},
    {"Fisk University": ["Bulldogs"]},
    {"Fitchburg State": ["Falcons"]},
    {"Flagler College": ["Saints"]},
    {"Florida": ["Gators"]},
    {"Florida A and M University": ["Rattlers"]},
    {"Florida Atlantic University": ["Owls"]},
    {"Florida International University": ["Golden Panthers"]},
    {"Florida College": ["Falcons"]},
    {"Florida Institute of Technology": ["Panthers"]},
    {"Florida Gulf Coast University": ["Eagles"]},
    {"Florida Memorial University": ["Lions"]},
    {"Florida National University": ["Conquistadors"]},
    {"Florida Southern": ["Moccasins"]},
    {"Florida SouthWestern State College": ["College Buccaneers"]},
    {"Florida State College at Jacksonville": ["Blue Wave"]},
    {"Florida State University": ["Seminoles"]},
    {"Fordham University": ["Rams"]},
    {"Fort Hays State University": ["Tigers"]},
    {"Fort Valley State University": ["Wildcats"]},
    {"Francis Marion University": ["Patriots"]},
    {"Franklin University": ["Raiders"]},
    {"Franklin and Marshall College": ["Diplomats"]},
    {"Franklin College": ["Grizzlies"]},
    {"Freed Hardeman University": ["Lions", "Lady Lions"]},
    {"Friends University": ["Falcons"]},
    {"Fresno Pacific University": ["Sunbirds"]},
    {"Fresno State": ["Bulldogs"]},
    {"Frostburg State University": ["Bobcats"]},
    {"Furman University": ["Paladins"]},
    {"Geneva College": ["Golden Tornadoes"]},
    {"Gannon University": ["Golden Knights"]},
    {"Genesee Community College": ["Cougars"]},
    {"George Mason University": ["Patriots"]},
    {"George Washington University": ["Colonials"]},
    {"Georgetown College": ["Tigers"]},
    {"Georgetown University": ["Hoyas"]},
    {"Georgia": ["Bulldogs"]},
    {"Georgia Gwinnett College": ["Grizzlies"]},
    {"Georgia Southern University": ["Eagles", "Lady Eagles"]},
    {"Georgia State University": ["Panthers"]},
    {"Georgia Tech": ["Yellow Jackets"]},
    {"Georgian Court University": ["Lions"]},
    {"Gettysburg College": ["Bullets"]},
    {"Glenville State College": ["Pioneers", "Lady Pioneers"]},
    {"Gonzaga University": ["Bulldogs"]},
    {"Gordon College": ["Fighting Scots"]},
    {"Goshen College": ["Maple Leafs"]},
    {"Grace College": ["Lancers"]},
    {"Graceland University": ["Yellow Jackets"]},
    {"Grambling State University": ["Tigers", "Lady Tigers"]},
    {"Grand Canyon University": ["Lopes"]},
    {"Grand Valley State University": ["Lakers"]},
    {"Grand View University": ["Vikings"]},
    {"Wisconsin Green Bay": ["Phoenix"]},
    {"Greensboro College": ["Pride"]},
    {"Grinnell College": ["Pioneers"]},
    {"Guilford College": ["Quakers"]},
    {"Gulf Coast State College": ["Commodores"]},
    {"Gustavus Adolphus College": ["Golden Gusties"]},
    {"Hanover College": ["Panthers"]},
    {"Hampton University": ["Pirates"]},
    {"Hamilton College": ["Continentals"]},
    {"Harding University": ["Bison"]},
    {"Harris Stowe State University": ["Hornets"]},
    {"University of Hartford": ["Hawks"]},
    {"Harvard University": ["Crimson"]},
    {"Hastings College": ["Broncos"]},
    {"Hawaii": ["Rainbow Warriors", "Rainbows", "Warriors", "Rainbow Wahine"]},
    {"Hawaii Hilo": ["Vulcans"]},
    {"Heidelberg University": ["Student Princes"]},
    {"Henderson State University": ["Reddies"]},
    {"Hendrix College": ["Warriors"]},
    {"Herkimer County Community College": ["Generals"]},
    {"High Point University": ["Panthers"]},
    {"Hillsborough": ["Hawks"]},
    {"Hiram College": ["Terriers"]},
    {"Hobart College": ["Statesmen"]},
    {"Hofstra University": ["Pride"]},
    {"Hope College": ["Flying Dutchmen"]},
    {"Holy Cross College": ["Crusaders"]},
    {"Houston": ["Cougars"]},
    {"University of Houston Downtown": ["Gators"]},
    {"University of Houston Victoria": ["Jaguars"]},
    {"Howard University": ["Bison"]},
    {"Humboldt State University": ["Lumberjacks"]},
    {"Huntington University": ["Foresters"]},
    {"Idaho": ["Vandals"]},
    {"Idaho State University": ["Bengals"]},
    {"College of Idaho": ["Coyotes"]},
    {"Illinois Institute of Technology": ["Scarlet Hawks"]},
    {"Illinois": ["Fighting Illini"]},
    {"Illinois Chicago": ["Flames"]},
    {"University of Illinois at Springfield": ["Prairie Stars"]},
    {"Illinois College": ["Blue Boys", "Lady Blues"]},
    {"Illinois State University": ["Redbirds"]},
    {"Illinois Wesleyan University": ["Titans"]},
    {"Incarnate Word College": ["Cardinals"]},
    {"Indian River State College": ["Pioneers"]},
    {"Indiana University": ["Hoosiers"]},
    {"Indiana State University": ["Sycamores"]},
    {"Indianapolis University": ["Greyhounds"]},
    {"Indiana University Purdue University Fort Wayne": ["Mastodons"]},
    {"Indiana University Purdue University Indianapolis": ["Jaguars"]},
    {"Indiana University of Pennsylvania": ["Crimson Hawks"]},
    {"Indiana University Southeast": ["Grenadiers"]},
    {"Indiana Wesleyan University": ["Wildcats"]},
    {"Iona College": ["Gaels"]},
    {"Iowa": ["Hawkeyes"]},
    {"Iowa State University": ["Cyclones"]},
    {"Iowa Wesleyan College": ["Tigers"]},
    {"Ithaca College": ["Bombers"]},
    {"Jackson State University": ["Tigers", "Lady Tigers"]},
    {"Jacksonville University": ["Dolphins"]},
    {"Jacksonville State University": ["Gamecocks"]},
    {"James Madison University": ["Dukes"]},
    {"Jamestown College": ["Jimmies"]},
    {"John Brown University": ["Golden Eagles"]},
    {"John Carroll University": ["Blue Streaks"]},
    {"Johns Hopkins University": ["Blue Jays"]},
    {"John Jay College": ["Bloodhounds"]},
    {"Johnson and Wales University": ["Wildcats"]},
    {"Johnson C. Smith University": ["Golden Bulls"]},
    {"Judson University": ["Eagles"]},
    {"Johnson University Florida": ["Suns"]},
    {"Kalamazoo College": ["Fighting Hornets"]},
    {"Kansas": ["Jayhawks"]},
    {"Kansas State University": ["Wildcats"]},
    {"Kansas Wesleyan University": ["Coyotes"]},
    {"Kean University": ["Cougars"]},
    {"Keene State College": ["Owls"]},
    {"Keiser University": ["Sea Hawks"]},
    {"Kennesaw State University": ["Owls", "Lady Owls"]},
    {"Kent State University": ["Golden Flashes"]},
    {"Kentucky": ["Wildcats"]},
    {"Kentucky Christian University": ["Knights"]},
    {"Kentucky State University": ["Thorobreds", "Thorobrettes"]},
    {"Kentucky Wesleyan College": ["Panthers"]},
    {"Kenyon College": ["Lords", "Ladies"]},
    {"King University": ["Tornado"]},
    {"Knox College": ["Prairie Fire"]},
    {"Kutztown University": ["Golden Bears"]},
    {"La Salle University": ["Explorers"]},
    {"LaGrange College": ["Panthers"]},
    {"Lafayette College": ["Leopards"]},
    {"Lake Erie College": ["Storm"]},
    {"Lake Forest College": ["Foresters"]},
    {"Lake Sumter State College": ["Lakers"]},
    {"Lake Superior State University": ["Lakers"]},
    {"Lamar University": ["Cardinals", "Lady Cardinals"]},
    {"Langston University": ["Lions", "Lady Lions"]},
    {"Lawrence University": ["Vikings"]},
    {"Le Moyne College": ["Dolphins"]},
    {"Lebanon Valley College": ["Flying Dutchmen"]},
    {"Leech Lake": ["Lakers"]},
    {"Lehigh University": ["Mountain Hawks"]},
    {"LeMoyne Owen College": ["Magicians"]},
    {"Lesley University": ["Lynx"]},
    {"Liberty University": ["Flames", "Lady Flames"]},
    {"Life University": ["Running Eagles"]},
    {"Lincoln Christian College": ["Preachers", "Angels"]},
    {"Lincoln University, Missouri": ["Blue Tigers"]},
    {"Lincoln University, Pennsylvania": ["Lions"]},
    {"Lincoln Memorial University": ["Railsplitters"]},
    {"Lindenwood University": ["Lions"]},
    {"Lindsey Wilson College": ["Blue Raiders"]},
    {"Linfield College": ["Wildcats"]},
    {"Lipscomb University": ["Bisons", "Lady Bisons"]},
    {"Livingstone College": ["Blue Bears"]},
    {"Lock Haven University": ["Bald Eagles"]},
    {"Longwood University": ["Lancers"]},
    {"Loras College": ["Duhawks"]},
    {"Los Angeles City College": ["Cubs"]},
    {"Los Angeles Harbor College": ["Seahawks"]},
    {"Los Angeles Mission College": ["Eagles"]},
    {"Los Angeles Pierce College": ["Brahmas"]},
    {"Los Angeles Southwest College": ["Cougars"]},
    {"Los Angeles Trade Technical College": ["Beavers"]},
    {"Los Angeles Valley College": ["Monarchs"]},
    {"Louisiana Tech University": ["Bulldogs", "Lady Techsters"]},
    {"Louisiana Lafayette": ["Ragin' Cajuns"]},
    {"Louisiana Monroe": ["Warhawks"]},
    {"Louisiana State University": ["Tigers", "Lady Tigers"]},
    {"Louisiana State University of Alexandria": ["Generals"]},
    {"Louisville": ["Cardinals"]},
    {"Loyola University of Chicago": ["Ramblers"]},
    {"Loyola University of Maryland": ["Greyhounds"]},
    {"Loyola Marymount University": ["Lions"]},
    {"Loyola University of New Orleans": ["Wolfpack"]},
    {"Loyola University of Los Angeles": ["Lions"]},
    {"Lubbock Christian University": ["Chaparrals"]},
    {"Luther College": ["Norse"]},
    {"Lyndon State College": ["Hornets"]},
    {"Lynn": ["Fighting Knights"]},
    {"Macalester College": ["Scots"]},
    {"MacMurray College": ["Highlanders"]},
    {"Maine": ["Black Bears"]},
    {"Malone University": ["Pioneers"]},
    {"Stage College of Florida Manatee": ["Manatees"]},
    {"Manchester College": ["Spartans"]},
    {"Manhattan College": ["Jaspers", "Lady Jaspers"]},
    {"Mansfield University of Pennsylvania": ["Mountaineers"]},
    {"Marietta College": ["Pioneers"]},
    {"Marist College": ["Red Foxes"]},
    {"Marquette University": ["Golden Eagles"]},
    {"Marshall University": ["Thundering Herd"]},
    {"Mary Baldwin College": ["Fighting Squirrels"]},
    {"Maryland": ["Terrapins"]},
    {"University of Maryland, Baltimore County": ["Retrievers"]},
    {"Marywood University": ["Pacers"]},
    {"Massachusetts": ["Minutemen"]},
    {"Massachusetts Boston": ["Beacons"]},
    {"Massachusetts Lowell": ["River Hawks"]},
    {"Massachusetts Institute of Technology": ["Engineers"]},
    {"The Masters University": ["Mustangs"]},
    {"McDaniel College": ["Green Terror"]},
    {"McNeese State University": ["Cowboys", "Cowgirls"]},
    {"McMurry University": ["Indians"]},
    {"McPherson College": ["Bulldogs"]},
    {"Medaille College": ["Mavericks"]},
    {"Memphis": ["Tigers", "Lady Tigers"]},
    {"Mercer University": ["Bears"]},
    {"Mercyhurst College": ["Lakers"]},
    {"Messiah College": ["Falcons"]},
    {"Metropolitan State University of Denver": ["Roadrunners"]},
    {"Miami": ["Hurricanes"]},
    {"Miami Dade": ["Sharks"]},
    {"Miami University, Ohio": ["RedHawks"]},
    {"Michigan": ["Wolverines"]},
    {"Michigan State University": ["Spartans"]},
    {"Michigan Technological University": ["Huskies"]},
    {"MidAmerica Nazarene University": ["Pioneers"]},
    {"Middle Tennessee State University": ["Blue Raiders"]},
    {"Middlebury College": ["Panthers"]},
    {"Midland University": ["Warriors"]},
    {"Midwestern State University": ["Mustangs", "Lady Mustangs"]},
    {"Mills College": ["Cyclones"]},
    {"Milligan College": ["Buffaloes"]},
    {"Millsaps College": ["Majors"]},
    {"Millersville College": ["Marauders"]},
    {"Minnesota": ["Golden Gophers"]},
    {"Minnesota Crookston": ["Golden Eagles"]},
    {"Minnesota Duluth": ["Bulldogs"]},
    {"Minnesota Morris": ["Cougars"]},
    {"Minnesota State": ["Mavericks"]},
    {"Minnesota State University Moorhead": ["Dragons"]},
    {"Misericordia University": ["Cougars"]},
    {"Mississippi": ["Rebels"]},
    {"Mississippi College": ["Choctaws"]},
    {"Mississippi State University": ["Bulldogs", "Lady Bulldogs"]},
    {"Mississippi Valley State University": ["Delta Devils", "Devilettes"]},
    {"Missouri": ["Tigers"]},
    {"Missouri Kansas City": ["Kangaroos"]},
    {"Missouri St Louis": ["Tritons"]},
    {"Missouri Rolla": ["Engineers"]},
    {"Missouri Southern State University": ["Lions"]},
    {"Missouri Western State University": ["Griffons"]},
    {"Missouri State University": ["Bears", "Lady Bears"]},
    {"Missouri Valley College": ["Vikings"]},
    {"Massachusetts Institute of Technology": ["Engineers"]},
    {"Mobile University": ["Rams"]},
    {"Monmouth University": ["Hawks"]},
    {"Montana": ["Grizzlies"]},
    {"Montana State University": ["Bobcats"]},
    {"Montclair State University": ["Red Hawks"]},
    {"University of Montevallo": ["Falcons"]},
    {"Moravian College": ["Greyhounds"]},
    {"Morehead State University": ["Eagles"]},
    {"Morgan State University": ["Bears", "Lady Bears"]},
    {"Morningside College": ["Mustangs"]},
    {"Morrisville State College": ["Mustangs"]},
    {"Mount Mercy College": ["Mustangs"]},
    {"Mount St. Mary's University": ["Mountaineers"]},
    {"Mount Union College": ["Purple Raiders"]},
    {"Muhlenberg College": ["Mules"]},
    {"Murray State University": ["Racers", "Lady Racers"]},
    {"Muskingum University": ["Fighting Muskies"]},
    {"Navy": ["Midshipmen"]},
    {"Nebraska": ["Cornhuskers"]},
    {"Nebraska Kearney": ["Lopers"]},
    {"Nebraska Omaha": ["Mavericks"]},
    {"Nebraska Wesleyan University": ["Prairie Wolves"]},
    {"Nevada": ["Wolf Pack"]},
    {"University of Nevada, Las Vegas": ["Rebels", "Runnin' Rebels", "Lady Rebels"]},
    {"University of New England, Maine": ["Nor'easters"]},
    {"New Hampshire": ["Wildcats"]},
    {"New Haven": ["Chargers"]},
    {"New Jersey Institute of Technology": ["Highlanders"]},
    {"New Mexico": ["Lobos"]},
    {"New Mexico State University": ["Aggies"]},
    {"New Mexico Mining and Technology": ["Pygmies"]},
    {"New Orleans": ["Privateers and Lady Privateers"]},
    {"New York University": ["Violets"]},
    {"Niagara University": ["Purple Eagles"]},
    {"Nicholls State University": ["Colonels"]},
    {"Norfolk State University": ["Spartans"]},
    {"North Alabama": ["Lions"]},
    {"University of North Carolina, Asheville": ["Bulldogs"]},
    {"North Carolina": ["Tar Heels"]},
    {"University of North Carolina, Charlotte": ["49ers"]},
    {"University of North Carolina, Greensboro": ["Spartans"]},
    {"University of North Carolina, Pembroke": ["Braves"]},
    {"University of North Carolina, Wilmington": ["Seahawks"]},
    {"North Carolina A and T University": ["Aggies"]},
    {"North Carolina Central University": ["Eagles"]},
    {"North Carolina School of the Arts": ["Fighting Pickles"]},
    {"North Carolina State University": ["Wolfpack"]},
    {"North Dakota": ["Fighting Hawks"]},
    {"North Dakota State University": ["Bison"]},
    {"North Georgia": ["Nighthawks"]},
    {"North Florida": ["Ospreys"]},
    {"North Park University": ["Vikings"]},
    {"North Texas": ["Mean Green"]},
    {"Northeastern University, Boston": ["Huskies"]},
    {"Northeastern State University": ["Riverhawks"]},
    {"Northern Arizona University": ["Lumberjacks"]},
    {"Northern Colorado": ["Bears"]},
    {"Northern Illinois University": ["Huskies"]},
    {"Northern Iowa": ["Panthers"]},
    {"Northern Kentucky University": ["Norse"]},
    {"Northrop University": ["Black Knights"]},
    {"Northern Michigan University": ["Wildcats"]},
    {"Northern New Mexico College": ["Eagles"]},
    {"Northwest Christian University": ["Beacons"]},
    {"Northwest Florida": ["Raiders"]},
    {"Northwest Missouri State University": ["Bearcats"]},
    {"Northwestern University": ["Wildcats"]},
    {"Northwestern State University": ["Demons", "Lady Demons"]},
    {"Norwich University": ["Cadets"]},
    {"Notre Dame": ["Fighting Irish"]},
    {"Nova Southeastern University": ["Sharks"]},
    {"Oak Hills Christian College": ["Wolfpack"]},
    {"Oakland University": ["Golden Grizzlies"]},
    {"Oakton Community College": ["Raiders"]},
    {"Oberlin College": ["Yeomen"]},
    {"Occidental College": ["Tigers"]},
    {"Oglethorpe University": ["Stormy Petrels"]},
    {"Ohio University": ["Bobcats"]},
    {"Ohio Northern University": ["Polar Bears"]},
    {"Ohio State University": ["Buckeyes"]},
    {"Ohio Valley University": ["Fighting Scots"]},
    {"Ohio Wesleyan University": ["Battlin' Bishops"]},
    {"Oklahoma": ["Sooners"]},
    {"Oklahoma City University": ["Stars"]},
    {"Oklahoma State University": ["Cowboys", "Cowgirls"]},
    {"Oklahoma Panhandle State University": ["Aggies"]},
    {"Oklahoma Wesleyan University": ["Eagles"]},
    {"Ole Miss": ["Rebels"]},
    {"Old Dominion University": ["Monarchs", "Lady Monarchs"]},
    {"Olivet Nazarene University": ["Tigers"]},
    {"Oral Roberts University": ["Golden Eagles"]},
    {"Oregon": ["Ducks"]},
    {"Oregon State University": ["Beavers"]},
    {"Oregon Institute of Technology": ["Hustlin' Owls"]},
    {"Oswego State University": ["Great Lakers"]},
    {"Ouachita Baptist University": ["Tigers"]},
    {"College of the Ozarks": ["Bobcats"]},
    {"The Ozarks": ["Eagles"]},
    {"Pace University": ["Setters"]},
    {"Pacific": ["Tigers"]},
    {"Pacific University": ["Boxers"]},
    {"Pacific Lutheran University": ["Lutes"]},
    {"Palm Beach Atlantic": ["Sailfish"]},
    {"Palm Beach State College": ["Panthers"]},
    {"Park University": ["Pirates"]},
    {"Pasadena City College": ["Lancers"]},
    {"Pasco Hernando State College": ["Conquistadors"]},
    {"Pensacola Christian College": ["Eagles"]},
    {"Pensacola State College": ["Pirates"]},
    {"Pennsylvania": ["Quakers"]},
    {"Pennsylvania State University": ["Nittany Lions", "Lady Lions"]},
    {"Pepperdine University": ["Waves"]},
    {"University of Pikeville": ["Bears"]},
    {"Pittsburg State University": ["Gorillas"]},
    {"Pittsburgh": ["Panthers"]},
    {"Pittsburgh Bradford": ["Panthers"]},
    {"Pittsburgh Greensburg": ["Bobcats"]},
    {"Pittsburgh Johnstown": ["Mountain Cats"]},
    {"Pittsburgh Titusville": ["Panthers"]},
    {"Pitzer College": ["Sagehens"]},
    {"Point Loma Nazarene University": ["Sea Lions"]},
    {"Point Park University Pittsburgh, Pennsylvania": ["Pioneers"]},
    {"Point University": ["Skyhawks"]},
    {"Polk State College": ["Eagles"]},
    {"Pomona College": ["Sagehens"]},
    {"Portland": ["Pilots"]},
    {"Portland State University": ["Vikings"]},
    {"Post University": ["Eagles"]},
    {"Prairie View A&M University": ["Panthers", "Lady Panthers"]},
    {"Presbyterian College": ["Blue Hose"]},
    {"Princeton University": ["Tigers"]},
    {"Providence College": ["Friars"]},
    {"Puerto Rico": ["Tarzans", "Janes"]},
    {"Purdue University": ["Boilermakers"]},
    {"Purdue Calumet": ["Peregrines"]},
    {"Purdue Ft. Wayne": ["Mastodons"]},
    {"Quinnipiac University": ["Bobcats"]},
    {"Quincy University": ["Hawks"]},
    {"Radford University": ["Highlanders"]},
    {"Randolph Macon College": ["Yellow Jackets"]},
    {"Redlands": ["Bulldogs"]},
    {"Reed College": ["Griffins"]},
    {"Regis University": ["Rangers"]},
    {"Reinhardt University": ["Eagles"]},
    {"Rensselaer Polytechnic Institute": ["Engineers"]},
    {"Rhema College": ["Eagles"]},
    {"Richmond": ["Spiders"]},
    {"Rice University": ["Owls"]},
    {"Rider University": ["Broncs"]},
    {"Rhode Island": ["Rams"]},
    {"Rhode Island College": ["Anchormen"]},
    {"Rhode Island School of Design": ["Nads"]},
    {"Rhodes College": ["Lynx"]},
    {"Roanoke College": ["Maroons"]},
    {"Rochester": ["Yellow Jackets"]},
    {"Robert Morris, Pennsylvania": ["Colonials"]},
    {"Robert Morris University, Illinois": ["Eagles"]},
    {"Rochester Institute of Technology": ["Tigers"]},
    {"Rock Valley College": ["Golden Eagles"]},
    {"Rockford University": ["Regents"]},
    {"Rollins College": ["Tars"]},
    {"Rose Hulman Institute of Technology": ["Fightin Engineers"]},
    {"Rosemont College": ["Ravens"]},
    {"Rowan University": ["Profs"]},
    {"Rutgers University": ["Scarlet Knights"]},
    {"Rutgers Camden": ["Scarlet Raptors"]},
    {"Rutgers Newark": ["Scarlet Raiders"]},
    {"Sacramento State University": ["Hornets"]},
    {"Sacred Heart University": ["Pioneers"]},
    {"Saint Ambrose University": ["Fighting Bees", "Queen Bees"]},
    {"Saint Anselm College": ["Hawks"]},
    {"Saint Benedicts College": ["Blazers"]},
    {"Saint Bonaventure University": ["Bonnies"]},
    {"Saint Cloud State University": ["Huskies"]},
    {"Saint Edwards University": ["Hilltoppers"]},
    {"Saint Francis, Indiana": ["Cougars"]},
    {"Saint Francis College, New York": ["Terriers"]},
    {"Saint Francis University": ["Red Flash"]},
    {"Saint John Fisher": ["Cardinals"]},
    {"St. Johns River": ["Vikings"]},
    {"Saint Johns University, Minnesota": ["Johnnies"]},
    {"Saint Johns University, New York": ["Red Storm"]},
    {"Saint Josephs College, Indiana": ["Pumas"]},
    {"Saint Josephs College, New York City": ["Bears", "Lady Bears"]},
    {"Saint Josephs College on Long Island": ["Golden Eagles", "Lady Eagles"]},
    {"Saint Josephs University": ["Hawks"]},
    {"Saint Lawrence University": ["Saints"]},
    {"Saint Leo Lions": ["Saint Leo Lions"]},
    {"Saint Louis University": ["Billikens"]},
    {"Saint Louis College of Pharmacy": ["Eutectics"]},
    {"Saint Mary": ["Spires"]},
    {"Saint Marys College of California": ["Gaels"]},
    {"Saint Marys University of Minnesota": ["Cardinals"]},
    {"Saint Mary of the Woods College": ["Pomeroys"]},
    {"Saint Michaels College": ["Purple Knights"]},
    {"Saint Olaf College": ["Oles"]},
    {"St. Petersburg College": ["Titans"]},
    {"Saint Peters University": ["Peacocks", "Peahens"]},
    {"St. Thomas University Florida": ["Bobcats"]},
    {"Saint Thomas, Minnesota": ["Tommies"]},
    {"Saint Vincent College Latrobe, Pennsylvania": ["Bearcats"]},
    {"Saint Xavier University": ["Cougars"]},
    {"Salem International University": ["Tigers"]},
    {"Salem State University": ["Vikings"]},
    {"Salisbury University": ["Seagulls"]},
    {"Sam Houston State University": ["Bearkats"]},
    {"Samford University": ["Bulldogs"]},
    {"University of San Diego": ["Toreros"]},
    {"San Diego State University": ["Aztecs"]},
    {"San Francisco": ["Dons"]},
    {"San Jose State University": ["Spartans"]},
    {"Santa Clara University": ["Broncos"]},
    {"Santa Fe College": ["Saints"]},
    {"Savannah College of Art and Design": ["Bees"]},
    {"Savannah State University": ["Tigers", "Lady Tigers"]},
    {"Scottsdale Community College": ["Artichokes"]},
    {"Seattle University": ["Redhawks"]},
    {"Seattle Pacific University": ["Falcons"]},
    {"Seton Hall University": ["Pirates"]},
    {"Seton Hill University Greensburg, Pennsylvania": ["Griffins"]},
    {"Sewanee, The University of the South": ["Tigers"]},
    {"Siena College": ["Saints"]},
    {"Simmons College of Kentucky": ["Panthers"]},
    {"Simon's Rock College": ["Llamas"]},
    {"Simpson College": ["Storm"]},
    {"Shawnee State University": ["Bears"]},
    {"Shepherd University": ["Rams"]},
    {"Shimer College": ["Flaming Smelts"]},
    {"Shippensburg University of Pennsylvania": ["Red Raiders"]},
    {"Skidmore College": ["Thoroughbreds"]},
    {"Slippery Rock University": ["The Rock"]},
    {"South Alabama": ["Jaguars"]},
    {"South Carolina": ["Gamecocks"]},
    {"University of South Carolina Beaufort": ["Sand Sharks"]},
    {"South Carolina Upstate": ["Spartans"]},
    {"South Carolina State University": ["Bulldogs"]},
    {"South Dakota": ["Coyotes"]},
    {"South Dakota School of Mines and Technology": ["Hardrockers"]},
    {"South Dakota State University": ["Jackrabbits"]},
    {"South Florida": ["Bulls"]},
    {"Southeast Missouri State University": ["Redhawks"]},
    {"Southeastern": ["Fire"]},
    {"Southeastern Louisiana University": ["Lions", "Lady Lions"]},
    {"Southeastern Oklahoma State University": ["Savage Storm"]},
    {"Southeastern University": ["Fire"]},
    {"Southern Arkansas University": ["Muleriders", "Lady Muleriders"]},
    {"Southern California": ["Trojans", "Women of Troy"]},
    {"Southern University and A and M College": ["Jaguars"]},
    {"Southern Connecticut State University": ["Owls"]},
    {"Southern Illinois University, Carbondale": ["Salukis"]},
    {"Southern Illinois University, Edwardsville": ["Cougars"]},
    {"Southern Indiana University": ["Screaming Eagles"]},
    {"Southern Maine": ["Huskies"]},
    {"Southern Methodist University": ["Mustangs"]},
    {"Southern Mississippi": ["Golden Eagles"]},
    {"Southern Nazarene University": ["Crimson Storm"]},
    {"Southern New Hampshire": ["Penmen"]},
    {"Southern Utah University": ["Thunderbirds", "Lady Thunderbirds"]},
    {"Southern Virginia University": ["Knights"]},
    {"Southwest Minnesota State University": ["Mustangs"]},
    {"Southwest Baptist University": ["Bearcats"]},
    {"Southwestern College": ["Moundbuilders"]},
    {"Southwestern University": ["Pirates"]},
    {"Spring Hill College": ["Badgers"]},
    {"Springfield College": ["Pride"]},
    {"Saint Thomas": ["Bobcats"]},
    {"Stanford University": ["Cardinal"]},
    {"College of Staten Island": ["Dolphins"]},
    {"Stephen F. Austin State University": ["Lumberjacks", "Ladyjacks"]},
    {"Stetson University": ["Mad Hatters"]},
    {"Stockton University": ["Ospreys"]},
    {"Stonehill College": ["Skyhawks"]},
    {"State University of New York at Buffalo": ["Bulls"]},
    {"State University of New York at Brockport": ["Golden Eagles"]},
    {"State University of New York at Cortland": ["Red Dragons"]},
    {"State University of New York at Environmental Science and Forestry": ["Mighty Oaks"]},
    {"State University of New York at Fredonia": ["Blue Devils"]},
    {"State University of New York at Geneseo": ["Knights"]},
    {"State University of New York at Institute of Technology": ["Wildcats"]},
    {"State University of New York at New Paltz": ["Hawks"]},
    {"State University of New York at Oneonta": ["Red Dragons"]},
    {"State University of New York at Plattsburgh": ["Cardinals"]},
    {"State University of New York at Potsdam": ["Bears"]},
    {"State University of New York at Stony Brook": ["Seawolves"]},
    {"Sussex County Community College": ["Skylanders"]},
    {"Sweet Briar": ["Vixens"]},
    {"Syracuse University": ["Orange"]},
    {"Tabor College": ["Bluejays"]},
    {"Tallahassee Community College": ["Eagles"]},
    {"Tampa": ["Spartans"]},
    {"Tarleton State University": ["Texans", "Texanns"]},
    {"Taylor University": ["Trojans"]},
    {"The College of New Jersey": ["Lions"]},
    {"Temple University": ["Owls"]},
    {"Tennessee": ["Volunteers", "Lady Volunteers"]},
    {"Tennessee Chattanooga": ["Mocs"]},
    {"Tennessee Martin": ["Skyhawks"]},
    {"Tennessee State University": ["Tigers", "Lady Tigers"]},
    {"Tennessee Tech": ["Golden Eagles"]},
    {"Tennessee Temple University": ["Crusaders"]},
    {"Texas": ["Longhorns"]},
    {"Texas Arlington": ["Mavericks"]},
    {"Texas Brownsville": ["Ocelots"]},
    {"Texas Christian University": ["Horned Frogs"]},
    {"Texas Dallas": ["Comets"]},
    {"University of Texas at El Paso": ["Miners"]},
    {"Texas Pan American": ["Broncs", "Lady Broncs"]},
    {"Texas Permian Basin": ["Falcons"]},
    {"Texas Rio Grande Valley": ["Vaqueros"]},
    {"Texas San Antonio": ["Roadrunners"]},
    {"Texas Tyler": ["Patriots"]},
    {"Texas A and M University": ["Aggies"]},
    {"Texas A and M Commerce": ["Lions"]},
    {"Texas A and M Corpus Christi": ["Islanders"]},
    {"Texas A and M International": ["Dustdevils"]},
    {"Texas A and M Kingsville": ["Javelinas"]},
    {"Texas Lutheran University": ["Bulldogs"]},
    {"Texas Southern University": ["Tigers"]},
    {"Texas State University": ["Bobcats"]},
    {"Texas Tech University": ["Red Raiders", "Lady Raiders"]},
    {"Texas Wesleyan University": ["Rams", "Lady Rams"]},
    {"Thiel College Greenville, Pennsylvania": ["Tomcats"]},
    {"Thomas": ["Night Hawks"]},
    {"Thomas More College": ["Blue Rebels"]},
    {"Toccoa Falls College": ["Eagles"]},
    {"University of Toledo": ["Rockets"]},
    {"Towson State University": ["Tigers"]},
    {"Transylvania University": ["Pioneers"]},
    {"Trevecca Nazarene University": ["Trojans"]},
    {"Trine University": ["Thunder"]},
    {"Trinity Baptist": ["Eagles"]},
    {"Trinity Bible College": ["Lions"]},
    {"Trinity Christian College": ["Trolls"]},
    {"Trinity College Connecticut": ["Bantams"]},
    {"Trinity College Florida": ["Tigers"]},
    {"Trinity University Texas": ["Tigers"]},
    {"Troy University": ["Trojans"]},
    {"Truman State University": ["Bulldogs"]},
    {"Tufts University": ["Jumbos"]},
    {"Tulane University": ["Green Wave"]},
    {"Tulsa": ["Golden Hurricane"]},
    {"Turtle Mountain": ["Mighty Mikinocks"]},
    {"Tusculum College": ["Pioneers"]},
    {"Tuskegee University": ["Golden Tigers", "Lady Tigers"]},
    {"Union College Kentucky": ["Bulldogs", "Lady Bulldogs"]},
    {"Union College New York": ["Dutchmen", "Dutchwomen"]},
    {"Union University Tennessee": ["Bulldogs", "Lady Bulldogs"]},
    {"Utah": ["Utes", "Runnin' Utes", "Red Rocks"]},
    {"Upper Iowa University": ["Peacocks"]},
    {"Utah State University": ["Aggies"]},
    {"Utah Valley": ["Wolverines"]},
    {"Utica College": ["Pioneers"]},
    {"Valdosta State University": ["Blazers"]},
    {"Valparaiso University": ["Crusaders"]},
    {"Vanderbilt University": ["Commodores"]},
    {"Vassar College": ["Brewers"]},
    {"Vermont": ["Catamounts"]},
    {"Stevenson University": ["Mustangs"]},
    {"Villanova University": ["Wildcats"]},
    {"Vincennes University": ["Trailblazers"]},
    {"Virginia": ["Cavaliers"]},
    {"Virginia Commonwealth University": ["Rams"]},
    {"Virginia Military Institute": ["Keydets"]},
    {"Virginia State University": ["Trojans"]},
    {"Virginia Tech": ["Hokies"]},
    {"Virginia Union University": ["Panthers"]},
    {"Virginia Wesleyan College": ["Marlins"]},
    {"Viterbo University": ["V Hawks"]},
    {"Voorhees College": ["Tigers"]},
    {"Wabash College": ["Little Giants"]},
    {"Wagner": ["Seahawks"]},
    {"Wake Forest": ["Demon Deacons"]},
    {"Waldorf": ["Warriors"]},
    {"Walsh University": ["Cavaliers"]},
    {"Warner University": ["Royals"]},
    {"Wartburg": ["Knights"]},
    {"Washburn": ["Ichabods", "Lady Blues"]},
    {"University of Washington": ["Huskies"]},
    {"Washington University in Saint Louis": ["Bears"]},
    {"Washington and Jefferson": ["Presidents"]},
    {"Washington and Lee": ["Generals"]},
    {"Washington State University": ["Cougars"]},
    {"Wayland Baptist": ["Pioneers"]},
    {"Wayne State College": ["Wildcats"]},
    {"Wayne State University": ["Warriors"]},
    {"Webber International University": ["Warriors"]},
    {"Weber State University": ["Wildcats"]},
    {"Webster University": ["Gorloks"]},
    {"Wellesley College": ["Blue"]},
    {"Wentworth Institute of Technology": ["Leopards"]},
    {"Wesley College": ["Wolverines"]},
    {"Wesleyan": ["Cardinals"]},
    {"West Alabama": ["Tigers"]},
    {"West Chester": ["Golden Rams"]},
    {"West Florida": ["Argonauts"]},
    {"West Georgia": ["Wolves"]},
    {"West Liberty State": ["Hilltoppers", "Lady Toppers"]},
    {"West Texas A and M": ["Buffaloes"]},
    {"West Los Angeles College": ["Wildcats"]},
    {"West Virginia": ["Mountaineers"]},
    {"West Virginia State University": ["Yellow Jackets"]},
    {"West Virginia University at Parkersburg": ["Riverhawks"]},
    {"West Virginia Tech": ["Golden Bears", "Lady Golden Bears"]},
    {"West Virginia Wesleyan": ["Bobcats", "Lady Bobcats"]},
    {"Western Carolina": ["Catamounts", "Lady Catamounts"]},
    {"Western Connecticut State": ["Colonials"]},
    {"Western Illinois": ["Fighting Leathernecks", "Westerwinds"]},
    {"Western Kentucky University": ["Hilltoppers"]},
    {"Western Michigan University": ["Broncos"]},
    {"Western Nebraska Community College": ["Cougars"]},
    {"Western Oregon University": ["Wolves"]},
    {"Western Texas College": ["Westerners", "Lady Westerners"]},
    {"Western Washington University": ["Vikings"]},
    {"Westmont College": ["Warriors"]},
    {"Wheaton College Illinois": ["Thunder"]},
    {"Wheaton College Massachusetts": ["Lyons"]},
    {"Wheeling Jesuit": ["Cardinals"]},
    {"Whitman College": ["Missionaries"]},
    {"Whittier College": ["Poets"]},
    {"Wichita State University": ["Shockers"]},
    {"Widener University": ["Pride"]},
    {"Wiley College": ["Wildcats"]},
    {"Wilkes University": ["Colonels"]},
    {"College of William and Mary": ["Tribe"]},
    {"William Carey University": ["Crusaders"]},
    {"William Jewell College": ["Cardinals"]},
    {"William Paterson University": ["Pioneers"]},
    {"William Penn University": ["Statesmen", "Lady Statesmen"]},
    {"William Smith College": ["Herons"]},
    {"William Woods University": ["Owls"]},
    {"Williams": ["Ephs"]},
    {"Williston State College": ["Tetons"]},
    {"Wilmington College Ohio": ["Fighting Quakers"]},
    {"Winona State University": ["Warriors"]},
    {"Winston Salem State University": ["Rams", "Lady Rams"]},
    {"Winthrop University": ["Eagles"]},
    {"Wisconsin Eau Claire": ["Blugolds"]},
    {"Wisconsin Green Bay": ["Phoenix"]},
    {"Wisconsin La Crosse": ["Eagles"]},
    {"Wisconsin Madison": ["Badgers"]},
    {"Wisconsin Marathon County": ["Huskies"]},
    {"Wisconsin Marshfield Wood County": ["Marauders"]},
    {"Wisconsin Milwaukee": ["Panthers"]},
    {"Wisconsin Oshkosh": ["Titans"]},
    {"Wisconsin Parkside": ["Rangers"]},
    {"Wisconsin Platteville": ["Pioneers"]},
    {"Wisconsin Richland": ["Roadrunners"]},
    {"Wisconsin River Falls": ["Falcons"]},
    {"Wisconsin Rock County": ["Rattlesnakes"]},
    {"Wisconsin Sheboygan": ["Wombats"]},
    {"Wisconsin Steven's Point": ["Pointers"]},
    {"Wisconsin Stout": ["Blue Devils"]},
    {"Wisconsin Superior": ["Yellowjackets"]},
    {"Wisconsin Whitewater": ["Warhawks"]},
    {"Wittenberg": ["Tigers"]},
    {"Wofford": ["Terrier"]},
    {"Wooster": ["Fighting Scots"]},
    {"Worcester Polytechnic Institute": ["Engineers"]},
    {"Worcester State College": ["Lancers"]},
    {"Wright State": ["Raiders"]},
    {"Wyoming": ["Cowboys", "Cowgirls"]},
    {"Xavier University (Cincinnati)": ["Musketeers"]},
    {"Yale University": ["Bulldogs", "Elis"]},
    {"Yeshiva University": ["Maccabees"]},
    {"York College of Pennsylvania": ["Spartans"]},
    {"Youngstown State University": ["Penguins"]}
]

PAC12 = [
    {"University of Washington": ["Huskies"]},
    {"Washington State University": ["Cougars"]},
    {"University of Oregon": ["Ducks"]},
    {"Oregon State University": ["Beavers"]},
    {"University of California, Berkeley": ["Golden Bears"]},
    {"Stanford University": ["Cardinal"]},
    {"University of Arizona": ["Wildcats"]},
    {"Arizona State University": ["Sun Devils"]},
    {"University of Southern California": ["Trojans", "Women of Troy"]},
    {"University of California, Los Angeles?": ["Bruins"]},
    {"University of Utah?": ["Utes", "Runnin' Utes", "Red Rocks"]},
    {"University of Colorado?": ["Buffaloes"]}
]

BIG10 = [
    {"Indiana University": ["Hoosiers"]},
    {"Maryland": ["Terrapins"]},
    {"Michigan": ["Wolverines"]},
    {"Michigan State University": ["Spartans"]},
    {"Ohio State University": ["Buckeyes"]},
    {"Pennsylvania State University": ["Nittany Lions", "Lady Lions"]},
    {"Rutgers University": ["Scarlet Knights"]},
    {"Illinois": ["Fighting Illini"]},
    {"Iowa": ["Hawkeyes"]},
    {"Minnesota": ["Golden Gophers"]},
    {"Nebraska": ["Cornhuskers"]},
    {"Northwestern University": ["Wildcats"]},
    {"Purdue University": ["Boilermakers"]},
    {"Wisconsin Madison": ["Badgers"]},
    {"Johns Hopkins University": ["Blue Jays"]},
    {"Notre Dame": ["Fighting Irish"]},

]

QUESTIONS = PAC12 + BIG10
